name: quiz_game_v2
description: "A Simple Quiz Game By Using Classes And Basic Pillars Of OOP. It Has reset Button And Alert As Well"

homepage: https://github.com/KASRA10/QuizGame-v2.git
issue_tracker: https://github.com/KASRA10/QuizGame-v2.git
documentation: https://github.com/KASRA10/QuizGame-v2.git
repository: https://github.com/KASRA10/QuizGame-v2.git

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.8
  hugeicons: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  fonts:
    - family: LexendExa
      fonts:
        - asset: fonts/LexendExa.ttf
          style: normal
